version: '3'

services:

# 1. Container: 'Tweet Collector'
  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    environment:
    - API_KEY=${API_KEY}
    - API_SECRET=${API_SECRET}
    - ACCESS_TOKEN=${ACCESS_TOKEN}
    - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
  
# 2. Container: 'Mongo DB'
  mongodb:
    image: mongo
    ports:
    - 1420:27017 

# 3. Container: 'Postgres'
  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=lena
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=tweets
  

# 4. Container: 'ETL'
  etl_job:
    container_name: etl_job
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb


# 5. Container: 'Slackbot'
  slack_bot:
    container_name: slack_bot
    build: slackbot/
    volumes:
    - ./slackbot/:/app
    depends_on:
    - postgresdb
    - etl_job
    - mongodb
    - tweet_collector
    environment:
    - WEBHOOK_URL=${WEBHOOK_URL}


